// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";

export default (c: Context) => {
  const html = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/svg+xml" href="/aaronlodge49/favicon.svg" />
    <title>Aaron Lodge No. 49 F.&A.M. | Tucson, Arizona</title>
    <meta name="description" content="Aaron Lodge No. 49 Free & Accepted Masons - Tucson, Arizona. Chartered April 25th, 1955. Meeting at the historic Scottish Rite Cathedral in downtown Tucson." />
    <script type="module" crossorigin src="/aaronlodge49/assets/app.js"></script>
    <link rel="stylesheet" crossorigin href="/aaronlodge49/assets/app.css">
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>`;
  
  return c.html(html);
};