// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { readFileSync, existsSync } from "node:fs";

const DATA_FILE = "/tmp/demolay-reviews.json";

interface Review {
  memberId: string;
  email: string;
  reviewerName: string;
  ratings: {
    leadership: number;
    teamwork: number;
    attendance: number;
    punctuality: number;
    motivation: number;
    ritualWork: number;
    initiative: number;
    planning: number;
  };
  comments: string;
  timestamp: string;
}

export default async (c: Context) => {
  const authHeader = c.req.header("X-Review-Token");
  if (!authHeader) {
    return c.json({ error: "Authentication required" }, 401);
  }

  // Parse token to get current user email
  let currentUserEmail = "";
  try {
    const tokenData = JSON.parse(Buffer.from(authHeader, "base64url").toString());
    currentUserEmail = tokenData.email || "";
  } catch (e) {}

  // Read reviews from file
  let reviews: Review[] = [];
  if (existsSync(DATA_FILE)) {
    try {
      const data = readFileSync(DATA_FILE, "utf-8");
      reviews = JSON.parse(data);
    } catch (e) {}
  }

  return c.json({
    reviews: reviews,
    totalCount: reviews.length,
    userReviewed: reviews.filter((r) => r.email === currentUserEmail).map((r) => r.memberId),
  });
};