// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";

export default async (c: Context) => {
  const clientId = process.env.GOOGLE_CLIENT_ID || "";
  const clientSecret = process.env.GOOGLE_CLIENT_SECRET || "";
  
  return c.json({
    configured: {
      clientId: clientId ? true : false,
      clientIdLength: clientId.length,
      clientSecret: clientSecret ? true : false
    },
    redirectUri: "https://jaknyfe.zo.space/api/auth/callback",
    message: clientId 
      ? "OAuth is configured. Try clicking the login button."
      : "Missing GOOGLE_CLIENT_ID. Add it in Settings > Advanced > Secrets."
  });
};
