// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";

export default async (c: Context) => {
  // Return HTML that clears localStorage and shows logout confirmation
  return c.html(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>Logged Out</title>
        <meta charset="utf-8">
      </head>
      <body style="font-family: system-ui; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; background: #f0f0f0;">
        <div style="text-align: center; padding: 40px; background: white; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
          <h1 style="color: #002868;">Logged Out Successfully</h1>
          <p>You have been signed out of the review system.</p>
          <a href="/demolay-review" style="display: inline-block; margin-top: 20px; padding: 12px 24px; background: #002868; color: white; text-decoration: none; border-radius: 4px; font-weight: bold;">Sign In Again</a>
          <script>
            localStorage.removeItem('reviewToken');
          </script>
        </div>
      </body>
    </html>
  `);
};