// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";

export default async (c: Context) => {
  const envVars = Object.keys(process.env)
    .filter(k => k.includes("GOOGLE") || k.includes("CLIENT"))
    .reduce((acc, k) => {
      acc[k] = process.env[k] ? "[SET]" : "[EMPTY]";
      return acc;
    }, {} as Record<string, string>);
  
  return c.json({
    allEnvKeys: Object.keys(process.env).filter(k => k.includes("GOOGLE") || k.includes("CLIENT")),
    googleVars: envVars,
    expectedKeys: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
    clientIdValue: process.env.GOOGLE_CLIENT_ID ? `Length: ${process.env.GOOGLE_CLIENT_ID.length}` : "NOT SET"
  });
};
