// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";

const members = [
  { id: "steve-johnston", name: "Dad Steve Johnston", title: "Executive Officer", email: "executive.officer@azdemolay.org" },
  { id: "don-lowery", name: "Dad Don Lowery", title: "State Dad", email: "state.dad@azdemolay.org" },
  { id: "bill-enloe", name: "Dad Bill Enloe", title: "State Membership Advisor", email: "membership.advisor@azdemolay.org" },
  { id: "seth-baldwin", name: "SMC Seth Baldwin", title: "State Master Councilor", email: "smc@azdemolay.org" },
  { id: "kaden-hartley", name: "DSMC Kaden Hartley", title: "Deputy State Master Councilor", email: "dsmc@azdemolay.org" },
  { id: "cooper-pitman", name: "SSC Cooper Pitman", title: "State Senior Councilor", email: "ssc@azdemolay.org" },
  { id: "john-enloe", name: "SJC John Enloe", title: "State Junior Councilor", email: "sjc@azdemolay.org" },
  { id: "james-hendrickson", name: "Scribe James Hendrickson", title: "State Scribe", email: "scribe@azdemolay.org" },
];

export default async (c: Context) => {
  const token = c.req.header("X-Review-Token");
  if (!token) return c.json({ error: "No token" }, 401);

  try {
    const data = JSON.parse(atob(token));
    const userEmail = (data.email || "").toLowerCase();
    const matchedMember = members.find(m => (m.email || "").toLowerCase() === userEmail);
    
    return c.json({
      userEmail,
      matchedMember: matchedMember ? { id: matchedMember.id, name: matchedMember.name, title: matchedMember.title } : null,
      isSelfReviewEligible: !!matchedMember
    });
  } catch {
    return c.json({ error: "Invalid token" }, 400);
  }
};
