// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { readFileSync, existsSync, statSync } from "node:fs";

const DATA_FILE = "/tmp/demolay-reviews.json";

export default async (c: Context) => {
  try {
    if (!existsSync(DATA_FILE)) {
      return c.json({ exists: false, message: "File does not exist" });
    }
    const stats = statSync(DATA_FILE);
    const content = readFileSync(DATA_FILE, "utf-8");
    const data = JSON.parse(content);
    return c.json({
      exists: true,
      size: stats.size,
      reviewsCount: data.reviews?.length || 0,
      sample: data.reviews?.slice(0, 2).map((r: any) => ({ member: r.memberId, email: r.email })) || [],
    });
  } catch (err: any) {
    return c.json({ error: err.message });
  }
};
