// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const DATA_FILE = "/tmp/demolay-reviews.json";

interface Review {
  memberId: string;
  email: string;
  name: string;
  timestamp: string;
  ratings: {
    leadership: number;
    teamwork: number;
    attendance: number;
    punctuality: number;
    motivation: number;
    ritualWork: number;
    initiative: number;
    planning: number;
  };
  comments: string;
}

function loadReviews(): Review[] {
  try {
    if (existsSync(DATA_FILE)) {
      return JSON.parse(readFileSync(DATA_FILE, "utf-8"));
    }
  } catch {}
  return [];
}

function saveReviews(reviews: Review[]) {
  writeFileSync(DATA_FILE, JSON.stringify(reviews, null, 2));
}

function getTokenData(c: Context) {
  const token = c.req.header("X-Review-Token") || c.req.header("x-review-token");
  if (!token) return null;
  try {
    const decoded = Buffer.from(token, "base64url").toString();
    const sessionData = JSON.parse(decoded);
    if (sessionData.expiresAt && Date.now() > sessionData.expiresAt) {
      return null;
    }
    if (!sessionData.email?.endsWith("@azdemolay.org")) {
      return null;
    }
    return sessionData;
  } catch {
    return null;
  }
}

export default async (c: Context) => {
  const sessionData = getTokenData(c);
  if (!sessionData) {
    return c.json({ error: "Authentication required" }, 401);
  }

  const email = sessionData.email;

  if (c.req.method === "GET") {
    const memberId = c.req.query("memberId");
    const allReviews = loadReviews();
    const userReviews = allReviews.filter(r => r.email === email);
    
    if (memberId) {
      const review = userReviews.find(r => r.memberId === memberId);
      if (review) {
        return c.json({ reviewed: true, review });
      }
      return c.json({ reviewed: false });
    }
    
    return c.json({ reviewedMembers: userReviews.map(r => r.memberId) });
  }

  if (c.req.method === "POST") {
    const body = await c.req.json();
    const { memberId, ratings, comments } = body;

    if (!memberId || !ratings) {
      return c.json({ error: "Missing required fields" }, 400);
    }

    const allReviews = loadReviews();
    const existingIndex = allReviews.findIndex(
      r => r.email === email && r.memberId === memberId
    );

    const review: Review = {
      memberId,
      email,
      name: sessionData.name,
      timestamp: new Date().toISOString(),
      ratings,
      comments: comments || ""
    };

    if (existingIndex >= 0) {
      return c.json({ error: "You have already submitted a review for this member" }, 409);
    }

    allReviews.push(review);
    saveReviews(allReviews);

    return c.json({
      success: true,
      message: "Review submitted successfully",
      reviewId: `${email}-${memberId}-${Date.now()}`
    });
  }

  return c.json({ error: "Method not allowed" }, 405);
};
