// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";

export default async (c: Context) => {
  // Use custom header to avoid Cloudflare stripping Authorization
  const authHeader = c.req.header("X-Review-Token") || c.req.header("x-review-token");
  
  if (!authHeader) {
    return c.json({ authenticated: false, error: "Missing token" }, 401);
  }

  try {
    const decoded = Buffer.from(authHeader, "base64url").toString();
    const sessionData = JSON.parse(decoded);
    
    if (sessionData.expiresAt && Date.now() > sessionData.expiresAt) {
      return c.json({ authenticated: false, error: "Session expired" }, 401);
    }
    
    return c.json({
      authenticated: true,
      email: sessionData.email,
      name: sessionData.name,
      picture: sessionData.picture
    });
    
  } catch (err) {
    console.error("Auth validation error:", err);
    return c.json({ authenticated: false, error: "Invalid session" }, 401);
  }
};
