// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";

const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID || "";
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET || "";
const REDIRECT_URI = "https://jaknyfe.zo.space/api/auth/callback";

export default async (c: Context) => {
  const code = c.req.query("code");
  const error = c.req.query("error");

  if (error) {
    return c.html(`
      <!DOCTYPE html>
      <html>
        <head><title>Authentication Failed</title></head>
        <body style="font-family: system-ui; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; background: #fef2f2;">
          <div style="text-align: center; padding: 2rem; background: white; border-radius: 1rem; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">
            <h1 style="color: #dc2626; margin-bottom: 1rem;">Authentication Failed</h1>
            <p style="color: #374151;">${error}</p>
            <a href="/demolay-review" style="display: inline-block; margin-top: 1.5rem; padding: 0.75rem 1.5rem; background: #dc2626; color: white; text-decoration: none; border-radius: 0.5rem; font-weight: 500;">Try Again</a>
          </div>
        </body>
      </html>
    `, 400);
  }

  if (!code) {
    return c.html(`
      <!DOCTYPE html>
      <html>
        <head><title>Invalid Request</title></head>
        <body style="font-family: system-ui; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; background: #fef2f2;">
          <div style="text-align: center; padding: 2rem; background: white; border-radius: 1rem; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">
            <h1 style="color: #dc2626; margin-bottom: 1rem;">Invalid Request</h1>
            <p style="color: #374151;">Missing authorization code</p>
            <a href="/demolay-review" style="display: inline-block; margin-top: 1.5rem; padding: 0.75rem 1.5rem; background: #dc2626; color: white; text-decoration: none; border-radius: 0.5rem; font-weight: 500;">Try Again</a>
          </div>
        </body>
      </html>
    `, 400);
  }

  if (!GOOGLE_CLIENT_ID || !GOOGLE_CLIENT_SECRET) {
    return c.html(`
      <!DOCTYPE html>
      <html>
        <head><title>Configuration Error</title></head>
        <body style="font-family: system-ui; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; background: #fef2f2;">
          <div style="text-align: center; padding: 2rem; background: white; border-radius: 1rem; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">
            <h1 style="color: #dc2626; margin-bottom: 1rem;">Configuration Error</h1>
            <p style="color: #374151;">OAuth credentials not configured</p>
            <a href="/demolay-review" style="display: inline-block; margin-top: 1.5rem; padding: 0.75rem 1.5rem; background: #dc2626; color: white; text-decoration: none; border-radius: 0.5rem; font-weight: 500;">Try Again</a>
          </div>
        </body>
      </html>
    `, 500);
  }

  try {
    const tokenResponse = await fetch("https://oauth2.googleapis.com/token", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        code,
        client_id: GOOGLE_CLIENT_ID,
        client_secret: GOOGLE_CLIENT_SECRET,
        redirect_uri: REDIRECT_URI,
        grant_type: "authorization_code"
      })
    });

    const tokens = await tokenResponse.json();

    if (!tokenResponse.ok) {
      return c.html(`
        <!DOCTYPE html>
        <html>
          <head><title>Authentication Failed</title></head>
          <body style="font-family: system-ui; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; background: #fef2f2;">
            <div style="text-align: center; padding: 2rem; background: white; border-radius: 1rem; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">
              <h1 style="color: #dc2626; margin-bottom: 1rem;">Token Exchange Failed</h1>
              <p style="color: #374151;">${tokens.error_description || tokens.error || "Unknown error"}</p>
              <a href="/demolay-review" style="display: inline-block; margin-top: 1.5rem; padding: 0.75rem 1.5rem; background: #dc2626; color: white; text-decoration: none; border-radius: 0.5rem; font-weight: 500;">Try Again</a>
            </div>
          </body>
        </html>
      `, 400);
    }

    const userResponse = await fetch("https://openidconnect.googleapis.com/v1/userinfo", {
      headers: { Authorization: `Bearer ${tokens.access_token}` }
    });

    const userInfo = await userResponse.json();

    if (!userResponse.ok) {
      return c.html(`
        <!DOCTYPE html>
        <html>
          <head><title>Authentication Failed</title></head>
          <body style="font-family: system-ui; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; background: #fef2f2;">
            <div style="text-align: center; padding: 2rem; background: white; border-radius: 1rem; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">
              <h1 style="color: #dc2626; margin-bottom: 1rem;">Failed to Fetch User Info</h1>
              <p style="color: #374151;">Could not retrieve your profile from Google</p>
              <a href="/demolay-review" style="display: inline-block; margin-top: 1.5rem; padding: 0.75rem 1.5rem; background: #dc2626; color: white; text-decoration: none; border-radius: 0.5rem; font-weight: 500;">Try Again</a>
            </div>
          </body>
        </html>
      `, 400);
    }

    const email = userInfo.email;
    const emailDomain = email?.split("@")[1];

    if (emailDomain !== "azdemolay.org") {
      return c.html(`
        <!DOCTYPE html>
        <html>
          <head><title>Access Denied</title></head>
          <body style="font-family: system-ui; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; background: #fef3c7;">
            <div style="text-align: center; padding: 2rem; background: white; border-radius: 1rem; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">
              <h1 style="color: #f59e0b; margin-bottom: 1rem;">Access Denied</h1>
              <p style="color: #374151; margin-bottom: 0.5rem;">Only @azdemolay.org email addresses are allowed.</p>
              <p style="color: #6b7280; font-size: 0.875rem;">You signed in with: ${email}</p>
              <a href="/demolay-review" style="display: inline-block; margin-top: 1.5rem; padding: 0.75rem 1.5rem; background: #f59e0b; color: white; text-decoration: none; border-radius: 0.5rem; font-weight: 500;">Try Again</a>
            </div>
          </body>
        </html>
      `, 403);
    }

    // Create session data
    const sessionData = {
      email,
      name: userInfo.name || email.split("@")[0],
      picture: userInfo.picture,
      accessToken: tokens.access_token,
      expiresAt: Date.now() + (tokens.expires_in * 1000)
    };

    // Encode as base64url
    const sessionToken = Buffer.from(JSON.stringify(sessionData)).toString("base64url");

    // Return HTML that stores token and redirects
    return c.html(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Login Successful</title>
          <meta charset="utf-8">
        </head>
        <body style="font-family: system-ui; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; background: #f0fdf4;">
          <div style="text-align: center;">
            <div style="width: 48px; height: 48px; border: 4px solid #86efac; border-top-color: #16a34a; border-radius: 50%; animation: spin 1s linear infinite; margin: 0 auto 1rem;"></div>
            <h2 style="color: #16a34a; margin: 0 0 0.5rem;">Login successful!</h2>
            <p style="color: #374151; margin: 0;">Redirecting you to the review page...</p>
          </div>
          <style>
            @keyframes spin { to { transform: rotate(360deg); } }
          </style>
          <script>
            (function() {
              try {
                var token = '${sessionToken}';
                localStorage.setItem('reviewToken', token);
                console.log('Auth token saved');
                window.location.replace('/demolay-review');
              } catch(e) {
                console.error('Auth save error:', e);
                document.body.innerHTML = '<div style="text-align:center;padding:2rem;"><h2 style="color:#dc2626;">Error saving login</h2><p>' + e.message + '</p><a href="/demolay-review">Go to login page</a></div>';
              }
            })();
          </script>
        </body>
      </html>
    `);

  } catch (err) {
    console.error("OAuth callback error:", err);
    return c.html(`
      <!DOCTYPE html>
      <html>
        <head><title>Authentication Failed</title></head>
        <body style="font-family: system-ui; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; background: #fef2f2;">
          <div style="text-align: center; padding: 2rem; background: white; border-radius: 1rem; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">
            <h1 style="color: #dc2626; margin-bottom: 1rem;">Authentication Failed</h1>
            <p style="color: #374151;">An unexpected error occurred</p>
            <pre style="text-align: left; background: #f3f4f6; padding: 1rem; border-radius: 0.5rem; margin-top: 1rem; font-size: 0.75rem;">${err instanceof Error ? err.message : String(err)}</pre>
            <a href="/demolay-review" style="display: inline-block; margin-top: 1.5rem; padding: 0.75rem 1.5rem; background: #dc2626; color: white; text-decoration: none; border-radius: 0.5rem; font-weight: 500;">Try Again</a>
          </div>
        </body>
      </html>
    `, 500);
  }
};
