// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import type { Context } from "hono";

const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID || "";
const REDIRECT_URI = "https://jaknyfe.zo.space/api/auth/callback";

export default async (c: Context) => {
  console.log("OAuth init - Client ID present:", GOOGLE_CLIENT_ID ? "yes" : "no");
  
  if (!GOOGLE_CLIENT_ID) {
    return c.json({ 
      error: "Google OAuth not configured",
      detail: "GOOGLE_CLIENT_ID environment variable is missing. Please add it in Settings > Advanced > Secrets."
    }, 500);
  }

  const state = Math.random().toString(36).substring(2) + Date.now().toString(36);
  
  const params = new URLSearchParams({
    client_id: GOOGLE_CLIENT_ID,
    redirect_uri: REDIRECT_URI,
    response_type: "code",
    scope: "openid email profile",
    state: state,
    hd: "azdemolay.org"
  });

  return c.redirect(`https://accounts.google.com/o/oauth2/v2/auth?${params.toString()}`);
};
