// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
export default function BuildErrorPage() {
  return (
    <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "system-ui, sans-serif", background: "#fafafa", color: "#111" }}>
      <div style={{ textAlign: "center", maxWidth: 420, padding: "2rem" }}>
        <h2 style={{ fontSize: "1.25rem", fontWeight: 600, marginBottom: "0.5rem" }}>This page has a build error</h2>
        <p style={{ color: "#666", fontSize: "0.9rem" }}>The space owner has been notified.</p>
      </div>
    </div>
  );
}
