// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { Star, Lock, CheckCircle2 } from "lucide-react";

const AZ_BLUE = "#002868";
const AZ_RED = "#BF0A30";
const AZ_GOLD = "#FFD700";
const AZ_COPPER = "#C47A6B";
const LIGHT_BLUE_BG = "linear-gradient(180deg, #e6f0ff 0%, #cce5ff 50%, #b3d9ff 100%)";

const members = [
  { id: "steve-johnston", name: "Dad Steve Johnston", title: "Executive Officer", email: "executive.officer@azdemolay.org" },
  { id: "don-lowery", name: "Dad Don Lowery", title: "State Dad", email: "state.officer.director@azdemolay.org" },
  { id: "bill-enloe", name: "Dad Bill Enloe", title: "State Membership Advisor", email: "membership.advisor@azdemolay.org" },
  { id: "seth-baldwin", name: "SMC Seth Baldwin", title: "State Master Councilor", email: "smc@azdemolay.org" },
  { id: "kaden-hartley", name: "DSMC Kaden Hartley", title: "Deputy State Master Councilor", email: "dsmc@azdemolay.org" },
  { id: "cooper-pitman", name: "SSC Cooper Pitman", title: "State Senior Councilor", email: "ssc@azdemolay.org" },
  { id: "john-enloe", name: "SJC John Enloe", title: "State Junior Councilor", email: "sjc@azdemolay.org" },
  { id: "james-hendrickson", name: "Scribe James Hendrickson", title: "State Scribe", email: "scribe@azdemolay.org" },
];

const DAD_EMAILS = ["state.officer.director@azdemolay.org", "state.dad@azdemolay.org", "membership.advisor@azdemolay.org"];

export default function Landing() {
  const [auth, setAuth] = useState<any>(null);
  const [reviewedMembers, setReviewedMembers] = useState<string[]>([]);
  const [isSelfReview, setIsSelfReview] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => { checkAuth(); }, []);

  const checkAuth = async () => {
    const token = localStorage.getItem("reviewToken");
    if (!token) { window.location.href = "/api/auth/google"; return; }
    try {
      const res = await fetch("/api/auth/me", { headers: { "X-Review-Token": token } });
      const data = await res.json();
      if (data.authenticated) {
        setAuth(data);
        checkReviewed(token);
        const userEmail = (data.email || "").toLowerCase();
        const selfMember = members.find(m => (m.email || "").toLowerCase() === userEmail);
        if (selfMember) setIsSelfReview(selfMember.id);
      } else {
        localStorage.removeItem("reviewToken");
        window.location.href = "/api/auth/google";
      }
    } catch {
      localStorage.removeItem("reviewToken");
      window.location.href = "/api/auth/google";
    }
  };

  const checkReviewed = async (token: string) => {
    try {
      const res = await fetch("/api/reviews/submit?memberId=test", { headers: { "X-Review-Token": token } });
      const data = await res.json();
      if (data.reviewedMembers) setReviewedMembers(data.reviewedMembers);
    } catch {}
    setLoading(false);
  };

  const handleLogout = () => {
    localStorage.removeItem("reviewToken");
    window.location.href = "https://accounts.google.com/logout";
  };

  if (!auth || loading) return (
    <div className="min-h-screen flex items-center justify-center" style={{ background: LIGHT_BLUE_BG }}>
      <div className="text-center"><div className="w-12 h-12 border-4 border-t-transparent rounded-full animate-spin mx-auto mb-4" style={{ borderColor: AZ_GOLD, borderTopColor: "transparent" }} /><p style={{ color: AZ_BLUE }}>Loading...</p></div>
    </div>
  );

  const isDad = DAD_EMAILS.includes((auth?.email || "").toLowerCase());

  return (
    <div className="min-h-screen" style={{ background: LIGHT_BLUE_BG }}>
      <div className="py-6" style={{ background: `linear-gradient(135deg, ${AZ_BLUE} 0%, ${AZ_RED} 100%)` }}>
        <div className="max-w-6xl mx-auto px-4">
          <h1 className="text-3xl font-bold text-center text-white" style={{ textShadow: "2px 2px 4px rgba(0,0,0,0.5)" }}>Arizona DeMolay 360° Review</h1>
          <p className="text-center mt-2 text-white" style={{ opacity: 0.9 }}>State Association Member Evaluation</p>
        </div>
      </div>
      <main className="max-w-6xl mx-auto px-4 py-8">
        <div className="mb-6 flex justify-between items-center">
          <div className="flex items-center gap-3">
            {auth.picture ? <img src={auth.picture} alt="Profile" className="w-10 h-10 rounded-full border-2" style={{ borderColor: AZ_GOLD }} /> : <div className="w-10 h-10 rounded-full flex items-center justify-center font-bold text-lg" style={{ background: AZ_GOLD, color: AZ_BLUE }}>{auth.name?.[0]}</div>}
            <div><p className="font-semibold text-lg" style={{ color: AZ_BLUE }}>{auth.name}</p><p className="text-sm" style={{ color: AZ_COPPER }}>{auth.email}</p></div>
          </div>
          <button onClick={handleLogout} className="px-4 py-2 rounded-lg font-semibold text-white" style={{ background: AZ_RED }}>Logout</button>
        </div>
        <p className="text-center mb-8 text-lg" style={{ color: AZ_BLUE }}>Select a member to review their performance</p>
        {reviewedMembers.length === members.length && <div className="mb-8 p-6 rounded-xl text-center" style={{ background: `${AZ_GOLD}30`, border: `2px solid ${AZ_GOLD}` }}><p className="text-xl font-semibold mb-2" style={{ color: AZ_BLUE }}>All Reviews Complete!</p><p className="mb-4" style={{ color: AZ_COPPER }}>Thank you for completing all 8 reviews.</p><Link to="/demolay-review" className="inline-block px-6 py-3 rounded-lg font-semibold text-white" style={{ background: AZ_BLUE }}>View All Results</Link></div>}
        {isSelfReview && <div className="mb-6 p-4 rounded-lg" style={{ background: `${AZ_RED}20`, borderLeft: `4px solid ${AZ_RED}` }}><p className="font-semibold" style={{ color: AZ_RED }}>Self-review disabled</p><p className="text-sm" style={{ color: AZ_COPPER }}>You cannot review yourself. Your data appears in results.</p></div>}
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          {members.map(member => {
            const isSelf = member.id === isSelfReview;
            const isReviewed = reviewedMembers.includes(member.id);
            if (isSelf) return <div key={member.id} className="rounded-xl p-4 opacity-70" style={{ background: "#e5e5e5", border: "2px dashed #999" }}><div className="flex items-start justify-between mb-3"><div className="w-12 h-12 rounded-full flex items-center justify-center" style={{ background: "#ccc" }}><Lock className="w-6 h-6" style={{ color: "#666" }} /></div>{isReviewed && <div className="p-1 rounded-full bg-green-500"><CheckCircle2 className="w-5 h-5 text-white" /></div>}</div><h3 className="font-semibold text-lg" style={{ color: "#666" }}>{member.name}</h3><p className="text-sm mb-3" style={{ color: "#888" }}>{member.title}</p><div className="flex items-center gap-2 text-sm" style={{ color: "#888" }}><Lock className="w-4 h-4" /><span>Self-review disabled</span></div></div>;
            return <Link key={member.id} to={`/review/${member.id}`} className={`rounded-xl p-4 transition-all hover:scale-105 shadow-lg ${isReviewed ? "opacity-80" : ""}`} style={{ background: "white", border: isReviewed ? `2px solid ${AZ_GOLD}` : "2px solid transparent" }}><div className="flex items-start justify-between mb-3"><div className="w-12 h-12 rounded-full flex items-center justify-center font-bold text-lg" style={{ background: isReviewed ? "#fbbf24" : AZ_GOLD, color: AZ_BLUE }}>{member.name.split(" ").map(n => n[0]).join("").slice(0, 2)}</div>{isReviewed && <div className="p-1 rounded-full bg-green-500"><CheckCircle2 className="w-5 h-5 text-white" /></div>}</div><h3 className="font-semibold text-lg" style={{ color: AZ_BLUE }}>{member.name}</h3><p className="text-sm mb-3" style={{ color: AZ_COPPER }}>{member.title}</p><div className="flex items-center gap-1 text-sm" style={{ color: isReviewed ? "#16a34a" : AZ_GOLD }}><Star className="w-4 h-4 fill-current" /><span>{isReviewed ? "Reviewed" : "Click to review"}</span></div></Link>;
          })}
        </div>
      </main>
    </div>
  );
}