// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { lazy, type ComponentType } from "react";

export interface PageRouteConfig {
  component: ComponentType;
  public: boolean;
}

export const pageRoutes: Record<string, PageRouteConfig> = {
  "/demolay-review": {
    component: lazy(() => import("./demolay-review")),
    public: true,
  },
  "/review": {
    component: lazy(() => import("./review")),
    public: false,
  },
  "/reviews": {
    component: lazy(() => import("./reviews")),
    public: false,
  },
  "/review/:memberId": {
    component: lazy(() => import("./review-:memberId")),
    public: false,
  },
  "/demolay-review/results": {
    component: lazy(() => import("./demolay-review-results")),
    public: false,
  },
};
