// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useState, useEffect } from "react";
import { useNavigate, Link } from "react-router-dom";
import { Star, AlertCircle } from "lucide-react";

const AZ_BLUE = "#002868";
const AZ_RED = "#BF0A30";
const AZ_GOLD = "#FFD700";
const AZ_COPPER = "#C47A6B";
const LIGHT_BLUE_BG = "linear-gradient(180deg, #e6f0ff 0%, #cce5ff 50%, #b3d9ff 100%)";

const members = [
  { id: "steve-johnston", name: "Dad Steve Johnston", title: "Executive Officer", email: "executive.officer@azdemolay.org" },
  { id: "don-lowery", name: "Dad Don Lowery", title: "State Dad", email: "state.officer.director@azdemolay.org" },
  { id: "bill-enloe", name: "Dad Bill Enloe", title: "State Membership Advisor", email: "membership.advisor@azdemolay.org" },
  { id: "seth-baldwin", name: "SMC Seth Baldwin", title: "State Master Councilor", email: "smc@azdemolay.org" },
  { id: "kaden-hartley", name: "DSMC Kaden Hartley", title: "Deputy State Master Councilor", email: "dsmc@azdemolay.org" },
  { id: "cooper-pitman", name: "SSC Cooper Pitman", title: "State Senior Councilor", email: "ssc@azdemolay.org" },
  { id: "john-enloe", name: "SJC John Enloe", title: "State Junior Councilor", email: "sjc@azdemolay.org" },
  { id: "james-hendrickson", name: "Scribe James Hendrickson", title: "State Scribe", email: "scribe@azdemolay.org" },
];

const attributes = [
  { key: "leadership", label: "Leadership" },
  { key: "teamwork", label: "Teamwork" },
  { key: "attendance", label: "Attendance" },
  { key: "punctuality", label: "Punctuality" },
  { key: "motivation", label: "Motivation" },
  { key: "ritualWork", label: "Ritual Work" },
  { key: "initiative", label: "Initiative" },
  { key: "planning", label: "Planning" },
];

export default function ReviewMember() {
  const navigate = useNavigate();
  const [auth, setAuth] = useState<any>(null);
  const [member, setMember] = useState<any>(null);
  const [ratings, setRatings] = useState<Record<string, number>>({});
  const [comments, setComments] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [isSelfReview, setIsSelfReview] = useState(false);

  useEffect(() => { checkAuth(); }, []);

  useEffect(() => {
    const pathParts = window.location.pathname.split("/");
    const memberId = pathParts[pathParts.length - 1];
    const found = members.find(m => m.id === memberId);
    if (found) {
      setMember(found);
      const userEmail = (auth?.email || "").toLowerCase();
      if ((found.email || "").toLowerCase() === userEmail) {
        setIsSelfReview(true);
      }
    }
  }, [auth]);

  const checkAuth = async () => {
    const token = localStorage.getItem("reviewToken");
    if (!token) { navigate("/"); return; }
    try {
      const res = await fetch("/api/auth/me", { headers: { "X-Review-Token": token } });
      const data = await res.json();
      if (data.authenticated) setAuth(data);
      else navigate("/");
    } catch { navigate("/"); }
  };

  const handleRating = (key: string, value: number) => setRatings({ ...ratings, [key]: value });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (Object.keys(ratings).length < 8) { setError("Please rate all attributes"); return; }
    setSubmitting(true); setError("");
    try {
      const token = localStorage.getItem("reviewToken");
      const res = await fetch("/api/reviews/submit", {
        method: "POST",
        headers: { "X-Review-Token": token || "", "Content-Type": "application/json" },
        body: JSON.stringify({ memberId: member.id, ratings, comments }),
      });
      if (res.ok) { navigate("/demolay-review"); }
      else { const d = await res.json(); setError(d.error || "Failed to submit"); }
    } catch { setError("Network error"); }
    setSubmitting(false);
  };

  const handleLogout = () => {
    localStorage.removeItem("reviewToken");
    window.location.href = "https://accounts.google.com/logout";
  };

  if (!auth || !member) return (
    <div className="min-h-screen flex items-center justify-center" style={{ background: LIGHT_BLUE_BG }}>
      <div className="text-center"><div className="w-12 h-12 border-4 border-t-transparent rounded-full animate-spin mx-auto mb-4" style={{ borderColor: AZ_GOLD, borderTopColor: "transparent" }} /><p style={{ color: AZ_BLUE }}>Loading...</p></div>
    </div>
  );

  if (isSelfReview) return (
    <div className="min-h-screen flex items-center justify-center" style={{ background: LIGHT_BLUE_BG }}>
      <div className="text-center p-8 rounded-xl" style={{ background: "white", border: `2px solid ${AZ_RED}` }}>
        <AlertCircle className="w-16 h-16 mx-auto mb-4" style={{ color: AZ_RED }} />
        <h2 className="text-2xl font-bold mb-2" style={{ color: AZ_RED }}>Self-Review Not Allowed</h2>
        <p className="mb-4" style={{ color: AZ_COPPER }}>You cannot review yourself.</p>
        <Link to="/demolay-review" className="px-6 py-2 rounded-lg text-white font-semibold" style={{ background: AZ_BLUE }}>Return to Members</Link>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen" style={{ background: LIGHT_BLUE_BG }}>
      <div className="py-6" style={{ background: `linear-gradient(135deg, ${AZ_BLUE} 0%, ${AZ_RED} 100%)` }}>
        <div className="max-w-2xl mx-auto px-4">
          <h1 className="text-2xl font-bold text-center text-white" style={{ textShadow: "2px 2px 4px rgba(0,0,0,0.5)" }}>360° Review</h1>
        </div>
      </div>
      <main className="max-w-2xl mx-auto px-4 py-8">
        <div className="mb-6 flex justify-between items-center">
          <Link to="/demolay-review" className="px-4 py-2 rounded-lg font-semibold text-white" style={{ background: AZ_BLUE }}>← Back</Link>
          <button onClick={handleLogout} className="px-4 py-2 rounded-lg font-semibold text-white" style={{ background: AZ_RED }}>Logout</button>
        </div>

        <div className="p-6 rounded-xl mb-6" style={{ background: "white", border: `2px solid ${AZ_GOLD}` }}>
          <h2 className="text-2xl font-bold mb-2" style={{ color: AZ_BLUE }}>{member.name}</h2>
          <p className="text-lg" style={{ color: AZ_COPPER }}>{member.title}</p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          {attributes.map(attr => (
            <div key={attr.key} className="p-4 rounded-xl" style={{ background: "white" }}>
              <label className="block font-semibold mb-3" style={{ color: AZ_BLUE }}>{attr.label}</label>
              <div className="flex gap-2">
                {[1,2,3,4,5].map(val => (
                  <button type="button" key={val} onClick={() => handleRating(attr.key, val)}
                    className="w-12 h-12 rounded-lg font-bold transition-all hover:scale-110"
                    style={{ background: ratings[attr.key] === val ? AZ_BLUE : "#e5e5e5", color: ratings[attr.key] === val ? "white" : "#666" }}>
                    {val}
                  </button>
                ))}
              </div>
            </div>
          ))}

          <div className="p-4 rounded-xl" style={{ background: "white" }}>
            <label className="block font-semibold mb-2" style={{ color: AZ_BLUE }}>Comments (Optional)</label>
            <textarea value={comments} onChange={e => setComments(e.target.value)} rows={4}
              className="w-full p-3 rounded-lg border-2 focus:outline-none focus:border-blue-600" style={{ borderColor: "#e5e5e5" }}
              placeholder="Additional feedback..." />
          </div>

          {error && <div className="p-4 rounded-lg text-center" style={{ background: `${AZ_RED}20`, color: AZ_RED }}>{error}</div>}

          <button type="submit" disabled={submitting}
            className="w-full py-4 rounded-lg font-bold text-lg text-white transition-all hover:opacity-90 disabled:opacity-50"
            style={{ background: AZ_BLUE }}>
            {submitting ? "Submitting..." : "Submit Review"}
          </button>
        </form>
      </main>
    </div>
  );
}