// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useParams, Link } from "react-router-dom";
import { useState, useEffect } from "react";
import { ArrowLeft, Lock, CheckCircle, User } from "lucide-react";

type Member = {
  id: string;
  name: string;
  title: string;
  email: string;
};

const members: Member[] = [
  { id: "steve-johnston", name: "Dad Steve Johnston", title: "Executive Officer", email: "executive.officer@azdemolay.org" },
  { id: "don-lowery", name: "Dad Don Lowery", title: "State Dad", email: "state.officer.director@azdemolay.org" },
  { id: "bill-enloe", name: "Dad Bill Enloe", title: "State Membership Advisor", email: "membership@azdemolay.org" },
  { id: "seth-baldwin", name: "SMC Seth Baldwin", title: "State Master Councilor", email: "smc@azdemolay.org" },
  { id: "kaden-hartley", name: "DSMC Kaden Hartley", title: "Deputy State Master Councilor", email: "dsmc@azdemolay.org" },
  { id: "cooper-pitman", name: "SSC Cooper Pitman", title: "State Senior Councilor", email: "ssc@azdemolay.org" },
  { id: "john-enloe", name: "SJC John Enloe", title: "State Junior Councilor", email: "sjc@azdemolay.org" },
  { id: "james-hendrickson", name: "Scribe James Hendrickson", title: "State Scribe", email: "scribe@azdemolay.org" }
];

type User = {
  email: string;
  name: string;
  picture?: string;
};

export default function Review() {
  const { memberId } = useParams<{ memberId: string }>();
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);
  const [isSelfReview, setIsSelfReview] = useState(false);
  const [alreadyReviewed, setAlreadyReviewed] = useState(false);
  const [previousReview, setPreviousReview] = useState<any>(null);
  const [formData, setFormData] = useState({
    leadership: 3, teamwork: 3, attendance: 3, punctuality: 3,
    motivation: 3, ritualWork: 3, initiative: 3, planning: 3,
    comments: ""
  });
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);

  const member = members.find(m => m.id === memberId);

  const checkAuth = async () => {
    const token = localStorage.getItem('reviewToken');
    if (!token) { setLoading(false); return; }
    try {
      const res = await fetch('/api/auth/me', {
        headers: { 'X-Review-Token': token }
      });
      const data = await res.json();
      if (data.authenticated) {
        setUser(data);
        if (member && data.email === member.email) {
          setIsSelfReview(true);
        }
        checkExistingReview(token);
      }
    } catch (e) {}
    setLoading(false);
  };

  const checkExistingReview = async (token: string) => {
    if (!memberId) return;
    try {
      const res = await fetch(`/api/reviews/submit?memberId=${memberId}`, {
        headers: { 'X-Review-Token': token }
      });
      const data = await res.json();
      if (data.reviewed) {
        setAlreadyReviewed(true);
        setPreviousReview(data.review);
      }
    } catch (e) {}
  };

  useEffect(() => { checkAuth(); }, [memberId]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSelfReview || alreadyReviewed) return;
    const token = localStorage.getItem('reviewToken');
    if (!token) return;
    setSubmitting(true);
    try {
      const res = await fetch('/api/reviews/submit', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'X-Review-Token': token },
        body: JSON.stringify({ memberId, ratings: formData, comments: formData.comments })
      });
      if (res.ok) setSubmitted(true);
    } catch (e) {}
    setSubmitting(false);
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-[#002868] to-[#BF0A30]">
        <div className="text-white text-xl">Loading...</div>
      </div>
    );
  }

  if (!user) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-[#002868] to-[#BF0A30]">
        <div className="bg-white p-8 rounded-xl shadow-lg max-w-md w-full mx-4">
          <h2 className="text-2xl font-bold text-[#002868] mb-4">Authentication Required</h2>
          <p className="text-gray-600 mb-6">Please sign in to submit reviews.</p>
          <Link to="/demolay-review" className="block w-full py-3 bg-[#BF0A30] text-white rounded-lg font-semibold text-center hover:opacity-90">
            Back to Login
          </Link>
        </div>
      </div>
    );
  }

  if (!member) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-[#002868] to-[#BF0A30]">
        <div className="bg-white p-8 rounded-xl shadow-lg">
          <h2 className="text-2xl font-bold text-red-600">Member Not Found</h2>
          <Link to="/demolay-review" className="mt-4 block text-[#002868] hover:underline">Back to Members</Link>
        </div>
      </div>
    );
  }

  if (submitted) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-[#002868] to-[#BF0A30] p-8">
        <div className="max-w-2xl mx-auto">
          <div className="bg-white rounded-xl shadow-lg p-8 text-center">
            <CheckCircle className="w-20 h-20 text-green-500 mx-auto mb-4" />
            <h2 className="text-3xl font-bold text-[#002868] mb-2">Review Submitted!</h2>
            <p className="text-gray-600 mb-6">Your review for {member.name} has been recorded.</p>
            <Link to="/demolay-review" className="inline-block px-6 py-3 bg-[#BF0A30] text-white rounded-lg font-semibold hover:opacity-90">
              Back to Members
            </Link>
          </div>
        </div>
      </div>
    );
  }

  if (isSelfReview) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-[#002868] to-[#BF0A30] p-8">
        <div className="max-w-2xl mx-auto">
          <div className="bg-white rounded-xl shadow-lg p-8">
            <Lock className="w-16 h-16 text-yellow-500 mx-auto mb-4" />
            <h2 className="text-2xl font-bold text-center text-[#002868] mb-2">Cannot Review Yourself</h2>
            <p className="text-gray-600 text-center mb-6">You cannot submit a review for {member.name} as this is your own profile.</p>
            <Link to="/demolay-review" className="block w-full py-3 bg-[#BF0A30] text-white rounded-lg font-semibold text-center hover:opacity-90">
              Back to Members
            </Link>
          </div>
        </div>
      </div>
    );
  }

  if (alreadyReviewed) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-[#002868] to-[#BF0A30] p-8">
        <div className="max-w-2xl mx-auto">
          <div className="bg-white rounded-xl shadow-lg p-8">
            <CheckCircle className="w-16 h-16 text-green-500 mx-auto mb-4" />
            <h2 className="text-2xl font-bold text-center text-[#002868] mb-2">Already Reviewed</h2>
            <p className="text-gray-600 text-center mb-6">You have already submitted a review for {member.name}.</p>
            {previousReview && (
              <div className="bg-gray-50 p-4 rounded-lg mb-6">
                <h3 className="font-semibold text-[#002868] mb-2">Your Review</h3>
                <div className="grid grid-cols-2 gap-2 text-sm">
                  <div>Leadership: <span className="font-bold">{previousReview.ratings.leadership}</span></div>
                  <div>Teamwork: <span className="font-bold">{previousReview.ratings.teamwork}</span></div>
                  <div>Attendance: <span className="font-bold">{previousReview.ratings.attendance}</span></div>
                  <div>Punctuality: <span className="font-bold">{previousReview.ratings.punctuality}</span></div>
                  <div>Motivation: <span className="font-bold">{previousReview.ratings.motivation}</span></div>
                  <div>Ritual Work: <span className="font-bold">{previousReview.ratings.ritualWork}</span></div>
                  <div>Initiative: <span className="font-bold">{previousReview.ratings.initiative}</span></div>
                  <div>Planning: <span className="font-bold">{previousReview.ratings.planning}</span></div>
                </div>
                {previousReview.comments && (
                  <p className="mt-3 text-sm text-gray-600 italic">"{previousReview.comments}"</p>
                )}
              </div>
            )}
            <div className="flex gap-3">
              <Link to="/demolay-review" className="flex-1 py-3 bg-[#BF0A30] text-white rounded-lg font-semibold text-center hover:opacity-90">
                Back to Members
              </Link>
              <Link to="/demolay-review/results" className="flex-1 py-3 bg-[#002868] text-white rounded-lg font-semibold text-center hover:opacity-90">
                View All Results
              </Link>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#002868] to-[#BF0A30] p-4">
      <main className="max-w-3xl mx-auto">
        <Link to="/demolay-review" className="inline-flex items-center gap-2 text-white/80 hover:text-white mb-4">
          <ArrowLeft className="w-5 h-5" /> Back to Members
        </Link>

        <div className="bg-white rounded-xl shadow-lg overflow-hidden">
          <div className="bg-gradient-to-r from-[#002868] to-[#BF0A30] p-6 text-white">
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 rounded-full bg-white/20 flex items-center justify-center">
                <User className="w-7 h-7" />
              </div>
              <div>
                <h1 className="text-2xl font-bold">{member.name}</h1>
                <p className="text-white/80">{member.title}</p>
              </div>
            </div>
          </div>

          <form onSubmit={handleSubmit} className="p-6 space-y-6">
            <p className="text-gray-600">Please rate {member.name.split(' ').slice(-1)[0]} on the following attributes:</p>

            {['leadership', 'teamwork', 'attendance', 'punctuality', 'motivation', 'ritualWork', 'initiative', 'planning'].map((attr) => (
              <div key={attr} className="bg-gray-50 p-4 rounded-lg">
                <label className="block font-semibold text-[#002868] mb-3 capitalize">
                  {attr === 'ritualWork' ? 'Ritual Work' : attr}
                </label>
                <div className="flex gap-2">
                  {[1, 2, 3, 4, 5].map((num) => (
                    <button
                      key={num}
                      type="button"
                      onClick={() => setFormData({ ...formData, [attr]: num })}
                      className={`w-10 h-10 rounded-lg font-semibold transition-all ${
                        formData[attr as keyof typeof formData] === num
                          ? 'bg-[#BF0A30] text-white'
                          : 'bg-white border-2 border-gray-200 text-gray-600 hover:border-[#002868]'
                      }`}
                    >
                      {num}
                    </button>
                  ))}
                </div>
              </div>
            ))}

            <div>
              <label className="block font-semibold text-[#002868] mb-2">Additional Comments</label>
              <textarea
                value={formData.comments}
                onChange={(e) => setFormData({ ...formData, comments: e.target.value })}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#002868] focus:border-transparent"
                rows={4}
                placeholder="Optional feedback..."
              />
            </div>

            <button
              type="submit"
              disabled={submitting}
              className="w-full py-4 bg-gradient-to-r from-[#002868] to-[#BF0A30] text-white rounded-lg font-bold text-lg hover:opacity-90 disabled:opacity-50"
            >
              {submitting ? 'Submitting...' : 'Submit Review'}
            </button>
          </form>
        </div>
      </main>
    </div>
  );
}