// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useParams, Link } from "react-router-dom";
import { useState, useEffect } from "react";
import { Star, ArrowLeft, CheckCircle2, AlertCircle } from "lucide-react";

// Original Arizona Flag Colors
const AZ_BLUE = "#002868";
const AZ_RED = "#BF0A30";
const AZ_GOLD = "#FFD700";
const AZ_COPPER = "#C47A6B";

const members = [
  { id: "steve-johnston", name: "Dad Steve Johnston", title: "Executive Officer", email: "executive.officer@azdemolay.org" },
  { id: "don-lowery", name: "Dad Don Lowery", title: "State Dad", email: "state.dad@azdemolay.org" },
  { id: "bill-enloe", name: "Dad Bill Enloe", title: "State Membership Advisor", email: "membership.advisor@azdemolay.org" },
  { id: "seth-baldwin", name: "SMC Seth Baldwin", title: "State Master Councilor", email: "smc@azdemolay.org" },
  { id: "kaden-hartley", name: "DSMC Kaden Hartley", title: "Deputy State Master Councilor", email: "dsmc@azdemolay.org" },
  { id: "cooper-pitman", name: "SSC Cooper Pitman", title: "State Senior Councilor", email: "ssc@azdemolay.org" },
  { id: "john-enloe", name: "SJC John Enloe", title: "State Junior Councilor", email: "sjc@azdemolay.org" },
  { id: "james-hendrickson", name: "Scribe James Hendrickson", title: "State Scribe", email: "scribe@azdemolay.org" },
];

const attributes = [
  { id: "leadership", label: "Leadership" },
  { id: "teamwork", label: "Teamwork" },
  { id: "attendance", label: "Attendance" },
  { id: "punctuality", label: "Punctuality" },
  { id: "motivation", label: "Motivation" },
  { id: "ritualWork", label: "Ritual Work" },
  { id: "initiative", label: "Initiative" },
  { id: "planning", label: "Planning" },
];

export default function ReviewForm() {
  const { memberId } = useParams();
  const [auth, setAuth] = useState<any>(null);
  const [ratings, setRatings] = useState<Record<string, number>>({});
  const [comments, setComments] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [alreadyReviewed, setAlreadyReviewed] = useState(false);
  const [previousReview, setPreviousReview] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [isSelfReview, setIsSelfReview] = useState(false);

  const member = members.find((m) => m.id === memberId);

  useEffect(() => {
    checkAuth();
  }, []);

  const checkAuth = async () => {
    const token = localStorage.getItem("reviewToken");
    if (!token) {
      window.location.href = "/api/auth/google";
      return;
    }

    try {
      const res = await fetch("/api/auth/me", {
        headers: { "X-Review-Token": token },
      });
      const data = await res.json();

      if (data.authenticated && data.email) {
        setAuth(data);
        const userEmail = (data.email || "").toLowerCase();
        if (member && (member.email || "").toLowerCase() === userEmail) {
          setIsSelfReview(true);
        }
        checkExistingReview(token);
      } else {
        localStorage.removeItem("reviewToken");
        window.location.href = "/api/auth/google";
      }
    } catch (err) {
      localStorage.removeItem("reviewToken");
      window.location.href = "/api/auth/google";
    }
  };

  const checkExistingReview = async (token: string) => {
    if (!memberId) return;
    try {
      const res = await fetch(`/api/reviews/submit?memberId=${memberId}`, {
        headers: { "X-Review-Token": token },
      });
      const data = await res.json();
      if (data.reviewed) {
        setAlreadyReviewed(true);
        setPreviousReview(data.review);
        if (data.review?.ratings) {
          setRatings(data.review.ratings);
        }
        if (data.review?.comments) {
          setComments(data.review.comments);
        }
      }
    } catch (err) {
      console.error("Failed to check existing review");
    }
    setLoading(false);
  };

  const handleRating = (attribute: string, value: number) => {
    if (alreadyReviewed || isSelfReview) return;
    setRatings((prev) => ({ ...prev, [attribute]: value }));
  };

  const handleSubmit = async () => {
    if (!memberId || alreadyReviewed || isSelfReview) return;
    const token = localStorage.getItem("reviewToken");
    if (!token) return;

    setSubmitting(true);
    try {
      const res = await fetch("/api/reviews/submit", {
        method: "POST",
        headers: {
          "X-Review-Token": token,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          memberId,
          ratings,
          comments,
        }),
      });
      const data = await res.json();
      if (data.success) {
        setSubmitted(true);
        setTimeout(() => {
          window.location.href = "/demolay-review";
        }, 2000);
      }
    } catch (err) {
      console.error("Failed to submit review");
    }
    setSubmitting(false);
  };

  const handleLogout = () => {
    localStorage.removeItem("reviewToken");
    window.location.href = "/api/auth/google";
  };

  if (!member) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{ background: `linear-gradient(135deg, ${AZ_BLUE}20 0%, ${AZ_RED}20 100%)` }}>
        <div className="text-center">
          <p className="text-xl mb-4" style={{ color: AZ_BLUE }}>Member not found</p>
          <Link to="/demolay-review" className="text-lg hover:underline" style={{ color: AZ_COPPER }}>
            ← Back to members
          </Link>
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="min-h-screen" style={{ background: `linear-gradient(135deg, ${AZ_BLUE}20 0%, ${AZ_RED}20 100%)` }}>
        <div className="flex items-center justify-center min-h-screen">
          <div className="text-center">
            <div className="w-12 h-12 border-4 border-t-transparent rounded-full animate-spin mx-auto mb-4" style={{ borderColor: AZ_GOLD, borderTopColor: "transparent" }} />
            <p className="text-lg" style={{ color: AZ_BLUE }}>Loading...</p>
          </div>
        </div>
      </div>
    );
  }

  if (isSelfReview) {
    return (
      <div className="min-h-screen" style={{ background: `linear-gradient(135deg, ${AZ_BLUE}20 0%, ${AZ_RED}20 100%)` }}>
        <div className="py-6" style={{ background: `linear-gradient(135deg, ${AZ_BLUE} 0%, ${AZ_RED} 100%)` }}>
          <div className="max-w-4xl mx-auto px-4">
            <Link to="/demolay-review" className="text-white hover:opacity-80 flex items-center gap-2">
              <ArrowLeft className="w-5 h-5" />
              Back to Members
            </Link>
          </div>
        </div>
        <div className="flex items-center justify-center min-h-[60vh]">
          <div className="text-center p-8 rounded-xl bg-white shadow-lg max-w-md">
            <AlertCircle className="w-16 h-16 mx-auto mb-4" style={{ color: AZ_RED }} />
            <h2 className="text-2xl font-bold mb-2" style={{ color: AZ_BLUE }}>Self-Review Disabled</h2>
            <p className="mb-4" style={{ color: AZ_COPPER }}>You cannot review yourself.</p>
            <p className="text-sm mb-6" style={{ color: "#666" }}>Your performance data will be available in the results page.</p>
            <Link
              to="/demolay-review"
              className="inline-block px-6 py-3 rounded-lg font-semibold text-white"
              style={{ background: AZ_BLUE }}
            >
              Return to Members
            </Link>
          </div>
        </div>
      </div>
    );
  }

  if (alreadyReviewed) {
    return (
      <div className="min-h-screen" style={{ background: `linear-gradient(135deg, ${AZ_BLUE}20 0%, ${AZ_RED}20 100%)` }}>
        <div className="py-6" style={{ background: `linear-gradient(135deg, ${AZ_BLUE} 0%, ${AZ_RED} 100%)` }}>
          <div className="max-w-4xl mx-auto px-4">
            <Link to="/demolay-review" className="text-white hover:opacity-80 flex items-center gap-2">
              <ArrowLeft className="w-5 h-5" />
              Back to Members
            </Link>
          </div>
        </div>
        <div className="flex items-center justify-center min-h-[60vh]">
          <div className="text-center p-8 rounded-xl bg-white shadow-lg max-w-md">
            <CheckCircle2 className="w-16 h-16 mx-auto mb-4" style={{ color: "#22c55e" }} />
            <h2 className="text-2xl font-bold mb-2" style={{ color: AZ_BLUE }}>Already Reviewed</h2>
            <p className="mb-4" style={{ color: AZ_COPPER }}>You have already submitted a review for {member.name}.</p>
            <Link
              to="/demolay-review"
              className="inline-block px-6 py-3 rounded-lg font-semibold text-white"
              style={{ background: AZ_BLUE }}
            >
              Return to Members
            </Link>
          </div>
        </div>
      </div>
    );
  }

  if (submitted) {
    return (
      <div className="min-h-screen" style={{ background: `linear-gradient(135deg, ${AZ_BLUE}20 0%, ${AZ_RED}20 100%)` }}>
        <div className="flex items-center justify-center min-h-screen">
          <div className="text-center p-8 rounded-xl bg-white shadow-lg">
            <CheckCircle2 className="w-16 h-16 mx-auto mb-4" style={{ color: "#22c55e" }} />
            <h2 className="text-2xl font-bold mb-2" style={{ color: AZ_BLUE }}>Review Submitted!</h2>
            <p style={{ color: AZ_COPPER }}>Thank you for your feedback.</p>
          </div>
        </div>
      </div>
    );
  }

  const allRated = attributes.every((attr) => ratings[attr.id] !== undefined);

  return (
    <div className="min-h-screen pb-8" style={{ background: `linear-gradient(135deg, ${AZ_BLUE}20 0%, ${AZ_RED}20 100%)` }}>
      <div className="py-6" style={{ background: `linear-gradient(135deg, ${AZ_BLUE} 0%, ${AZ_RED} 100%)` }}>
        <div className="max-w-4xl mx-auto px-4">
          <Link to="/demolay-review" className="text-white hover:opacity-80 flex items-center gap-2 mb-4">
            <ArrowLeft className="w-5 h-5" />
            Back to Members
          </Link>
          <h1 className="text-3xl font-bold text-white">Review: {member.name}</h1>
          <p className="text-white mt-1" style={{ opacity: 0.9 }}>{member.title}</p>
        </div>
      </div>

      <main className="max-w-4xl mx-auto px-4 py-8">
        <div className="bg-white rounded-xl shadow-lg p-6 mb-6">
          <p className="text-lg mb-6" style={{ color: AZ_BLUE }}>
            Rate each attribute on a scale of 1-5:
          </p>

          {attributes.map((attr) => (
            <div key={attr.id} className="mb-6">
              <div className="flex justify-between items-center mb-2">
                <label className="font-semibold text-lg" style={{ color: AZ_BLUE }}>
                  {attr.label}
                </label>
                <span className="text-2xl font-bold" style={{ color: AZ_COPPER }}>
                  {ratings[attr.id] || "-"}
                </span>
              </div>
              <div className="flex gap-2">
                {[1, 2, 3, 4, 5].map((value) => (
                  <button
                    key={value}
                    onClick={() => handleRating(attr.id, value)}
                    className={`w-12 h-12 rounded-lg font-bold text-lg transition-all ${
                      ratings[attr.id] === value
                        ? "ring-2 ring-offset-2"
                        : "hover:scale-110"
                    }`}
                    style={{
                      background: ratings[attr.id] === value ? AZ_GOLD : "#f3f4f6",
                      color: ratings[attr.id] === value ? AZ_BLUE : "#9ca3af",
                      ringColor: AZ_GOLD,
                    }}
                  >
                    {value}
                  </button>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div className="bg-white rounded-xl shadow-lg p-6 mb-6">
          <label className="font-semibold text-lg block mb-2" style={{ color: AZ_BLUE }}>
            Additional Comments (Optional)
          </label>
          <textarea
            value={comments}
            onChange={(e) => setComments(e.target.value)}
            placeholder="Share any additional feedback..."
            className="w-full p-4 rounded-lg border-2 focus:outline-none focus:ring-2"
            style={{ borderColor: "#e5e7eb", minHeight: "120px" }}
          />
        </div>

        <button
          onClick={handleSubmit}
          disabled={!allRated || submitting}
          className="w-full py-4 rounded-xl font-bold text-lg text-white transition-all disabled:opacity-50 disabled:cursor-not-allowed"
          style={{ background: allRated ? AZ_BLUE : "#9ca3af" }}
        >
          {submitting ? "Submitting..." : "Submit Review"}
        </button>

        {!allRated && (
          <p className="text-center mt-4" style={{ color: AZ_COPPER }}>
            Please rate all attributes before submitting
          </p>
        )}
      </main>
    </div>
  );
}
