// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useState, useEffect } from "react";
import { Star, Lock, CheckCircle2 } from "lucide-react";

const AZ_BLUE = "#002868";
const AZ_RED = "#BF0A30";
const AZ_GOLD = "#FFD700";
const AZ_COPPER = "#C47A6B";

const members = [
  { id: "steve-johnston", name: "Dad Steve Johnston", title: "Executive Officer", email: "executive.officer@azdemolay.org" },
  { id: "don-lowery", name: "Dad Don Lowery", title: "State Dad", email: "state.dad@azdemolay.org" },
  { id: "bill-enloe", name: "Dad Bill Enloe", title: "State Membership Advisor", email: "membership.advisor@azdemolay.org" },
  { id: "seth-baldwin", name: "SMC Seth Baldwin", title: "State Master Councilor", email: "smc@azdemolay.org" },
  { id: "kaden-hartley", name: "DSMC Kaden Hartley", title: "Deputy State Master Councilor", email: "dsmc@azdemolay.org" },
  { id: "cooper-pitman", name: "SSC Cooper Pitman", title: "State Senior Councilor", email: "ssc@azdemolay.org" },
  { id: "john-enloe", name: "SJC John Enloe", title: "State Junior Councilor", email: "sjc@azdemolay.org" },
  { id: "james-hendrickson", name: "Scribe James Hendrickson", title: "State Scribe", email: "scribe@azdemolay.org" },
];

export default function ReviewMember() {
  const pathParts = window.location.pathname.split('/');
  const memberId = pathParts[pathParts.length - 1] || "";
  const member = members.find(m => m.id === memberId);
  const [auth, setAuth] = useState<any>(null);
  const [ratings, setRatings] = useState({ leadership: 3, teamwork: 3, attendance: 3, punctuality: 3, motivation: 3, ritualWork: 3, initiative: 3, planning: 3 });
  const [comment, setComment] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(true);
  const [alreadyReviewed, setAlreadyReviewed] = useState(false);
  const [isSelfReview, setIsSelfReview] = useState(false);

  useEffect(() => {
    checkAuth();
  }, []);

  const checkAuth = async () => {
    const token = localStorage.getItem("reviewToken");
    if (!token) {
      window.location.href = "/api/auth/google";
      return;
    }
    try {
      const res = await fetch("/api/auth/me", { headers: { "X-Review-Token": token } });
      const data = await res.json();
      if (data.authenticated) {
        setAuth(data);
        const userEmail = (data.email || "").toLowerCase();
        if (member && (member.email || "").toLowerCase() === userEmail) {
          setIsSelfReview(true);
          setLoading(false);
          return;
        }
        checkExistingReview(token);
      } else {
        localStorage.removeItem("reviewToken");
        window.location.href = "/api/auth/google";
      }
    } catch {
      localStorage.removeItem("reviewToken");
      window.location.href = "/api/auth/google";
    }
  };

  const checkExistingReview = async (token: string) => {
    try {
      const res = await fetch("/api/reviews/submit?memberId=" + memberId, { headers: { "X-Review-Token": token } });
      const data = await res.json();
      if (data.reviewed) {
        setAlreadyReviewed(true);
        setRatings(data.ratings);
        setComment(data.comments || "");
      }
    } catch {}
    setLoading(false);
  };

  const handleSubmit = async () => {
    const token = localStorage.getItem("reviewToken");
    if (!token || !member) return;
    try {
      const res = await fetch("/api/reviews/submit", {
        method: "POST",
        headers: { "X-Review-Token": token, "Content-Type": "application/json" },
        body: JSON.stringify({ memberId, ratings, comments: comment }),
      });
      const data = await res.json();
      if (data.success) setSubmitted(true);
    } catch {}
  };

  const handleLogout = () => {
    localStorage.removeItem("reviewToken");
    window.location.href = "/api/auth/google";
  };

  if (loading) return (
    <div className="min-h-screen flex items-center justify-center" style={{ background: `linear-gradient(135deg, ${AZ_BLUE}20 0%, ${AZ_RED}20 50%, ${AZ_GOLD}15 100%)` }}>
      <div className="text-center"><div className="w-12 h-12 border-4 border-t-transparent rounded-full animate-spin mx-auto mb-4" style={{ borderColor: AZ_GOLD, borderTopColor: "transparent" }} /><p style={{ color: AZ_BLUE }}>Loading...</p></div>
    </div>
  );

  if (!member) return (
    <div className="min-h-screen flex items-center justify-center" style={{ background: `linear-gradient(135deg, ${AZ_BLUE}20 0%, ${AZ_RED}20 50%, ${AZ_GOLD}15 100%)` }}>
      <div className="text-center p-8 rounded-xl bg-white shadow-lg"><h2 className="text-2xl font-bold mb-4" style={{ color: AZ_RED }}>Member Not Found</h2><a href="/demolay-review" className="px-6 py-3 rounded-lg font-semibold text-white" style={{ background: AZ_BLUE }}>Back to Members</a></div>
    </div>
  );

  if (isSelfReview) return (
    <div className="min-h-screen" style={{ background: `linear-gradient(135deg, ${AZ_BLUE}20 0%, ${AZ_RED}20 50%, ${AZ_GOLD}15 100%)` }}>
      <div className="py-6" style={{ background: `linear-gradient(135deg, ${AZ_BLUE} 0%, ${AZ_RED} 100%)` }}>
        <div className="max-w-2xl mx-auto px-4"><h1 className="text-2xl font-bold text-white text-center">Arizona DeMolay 360° Review</h1></div>
      </div>
      <div className="max-w-md mx-auto px-4 py-16 text-center">
        <div className="p-8 rounded-xl bg-white shadow-lg">
          <div className="w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4" style={{ background: `${AZ_RED}20` }}><Lock className="w-8 h-8" style={{ color: AZ_RED }} /></div>
          <h2 className="text-xl font-bold mb-2" style={{ color: AZ_RED }}>Self-Review Disabled</h2>
          <p className="mb-4" style={{ color: "#666" }}>You cannot review yourself. Your review data will be shown in the results.</p>
          <a href="/demolay-review" className="inline-block px-6 py-3 rounded-lg font-semibold text-white" style={{ background: AZ_BLUE }}>Back to Members</a>
        </div>
      </div>
    </div>
  );

  if (alreadyReviewed || submitted) return (
    <div className="min-h-screen" style={{ background: `linear-gradient(135deg, ${AZ_BLUE}20 0%, ${AZ_RED}20 50%, ${AZ_GOLD}15 100%)` }}>
      <div className="py-6" style={{ background: `linear-gradient(135deg, ${AZ_BLUE} 0%, ${AZ_RED} 100%)` }}>
        <div className="max-w-2xl mx-auto px-4"><h1 className="text-2xl font-bold text-white text-center">Arizona DeMolay 360° Review</h1></div>
      </div>
      <div className="max-w-md mx-auto px-4 py-16 text-center">
        <div className="p-8 rounded-xl bg-white shadow-lg">
          <div className="w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 bg-green-500"><CheckCircle2 className="w-8 h-8 text-white" /></div>
          <h2 className="text-xl font-bold mb-2" style={{ color: "#16a34a" }}>Review Submitted!</h2>
          <p className="mb-4" style={{ color: "#666" }}>You have already submitted a review for {member.name}.</p>
          <a href="/demolay-review" className="inline-block px-6 py-3 rounded-lg font-semibold text-white" style={{ background: AZ_BLUE }}>Back to Members</a>
        </div>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen" style={{ background: `linear-gradient(135deg, ${AZ_BLUE}20 0%, ${AZ_RED}20 50%, ${AZ_GOLD}15 100%)` }}>
      <div className="py-6" style={{ background: `linear-gradient(135deg, ${AZ_BLUE} 0%, ${AZ_RED} 100%)` }}>
        <div className="max-w-2xl mx-auto px-4"><h1 className="text-2xl font-bold text-white text-center">Arizona DeMolay 360° Review</h1></div>
      </div>
      <main className="max-w-2xl mx-auto px-4 py-8">
        <div className="mb-6 flex justify-between items-center">
          <a href="/demolay-review" className="px-4 py-2 rounded-lg font-semibold text-white" style={{ background: AZ_BLUE }}>← Back</a>
          <button onClick={handleLogout} className="px-4 py-2 rounded-lg font-semibold text-white" style={{ background: AZ_RED }}>Logout</button>
        </div>
        <div className="bg-white rounded-xl shadow-lg p-6">
          <div className="text-center mb-6">
            <h2 className="text-2xl font-bold" style={{ color: AZ_BLUE }}>{member.name}</h2>
            <p className="text-lg" style={{ color: AZ_COPPER }}>{member.title}</p>
          </div>
          <div className="space-y-4">
            {Object.entries({ leadership: "Leadership", teamwork: "Teamwork", attendance: "Attendance", punctuality: "Punctuality", motivation: "Motivation", ritualWork: "Ritual Work", initiative: "Initiative", planning: "Planning" }).map(([key, label]) => (
              <div key={key} className="flex items-center justify-between">
                <span className="font-medium" style={{ color: AZ_BLUE }}>{label}</span>
                <div className="flex gap-1">
                  {[1,2,3,4,5].map(n => (
                    <button key={n} onClick={() => setRatings(prev => ({ ...prev, [key]: n }))} className="p-1 rounded hover:scale-110 transition-transform">
                      <Star className="w-6 h-6" fill={n <= ratings[key as keyof typeof ratings] ? AZ_GOLD : "#e5e5e5"} color={n <= ratings[key as keyof typeof ratings] ? AZ_GOLD : "#e5e5e5"} />
                    </button>
                  ))}
                </div>
              </div>
            ))}
          </div>
          <div className="mt-6">
            <label className="block font-medium mb-2" style={{ color: AZ_BLUE }}>Comments (optional)</label>
            <textarea value={comment} onChange={e => setComment(e.target.value)} rows={3} className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2" style={{ borderColor: AZ_BLUE, focusRing: AZ_BLUE }} placeholder="Additional feedback..." />
          </div>
          <button onClick={handleSubmit} className="w-full mt-6 py-3 rounded-lg font-bold text-white transition-all hover:opacity-90" style={{ background: AZ_BLUE }}>Submit Review</button>
        </div>
      </main>
    </div>
  );
}