// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { ChevronRight, CheckCircle, Lock } from "lucide-react";

type Member = {
  id: string;
  name: string;
  title: string;
  email: string;
};

const members: Member[] = [
  { id: "steve-johnston", name: "Dad Steve Johnston", title: "Executive Officer", email: "executive.officer@azdemolay.org" },
  { id: "don-lowery", name: "Dad Don Lowery", title: "State Dad", email: "state.officer.director@azdemolay.org" },
  { id: "bill-enloe", name: "Dad Bill Enloe", title: "State Membership Advisor", email: "membership@azdemolay.org" },
  { id: "seth-baldwin", name: "SMC Seth Baldwin", title: "State Master Councilor", email: "smc@azdemolay.org" },
  { id: "kaden-hartley", name: "DSMC Kaden Hartley", title: "Deputy State Master Councilor", email: "dsmc@azdemolay.org" },
  { id: "cooper-pitman", name: "SSC Cooper Pitman", title: "State Service Councilor", email: "ssc@azdemolay.org" },
  { id: "john-enloe", name: "SJC John Enloe", title: "State Junior Councilor", email: "sjc@azdemolay.org" },
  { id: "james-hendrickson", name: "Scribe James Hendrickson", title: "State Scribe", email: "scribe@azdemolay.org" },
];

export default function Reviews() {
  const [user, setUser] = useState<{name: string; email: string} | null>(null);
  const [loading, setLoading] = useState(true);
  const [reviewedMembers, setReviewedMembers] = useState<string[]>([]);

  useEffect(() => {
    const checkAuth = async () => {
      const token = localStorage.getItem('reviewToken');
      if (!token) { setLoading(false); return; }
      try {
        const res = await fetch('/api/auth/me', { headers: { 'X-Review-Token': token } });
        const data = await res.json();
        if (data.authenticated) {
          setUser({ name: data.name, email: data.email });
          const reviewedRes = await fetch('/api/reviews/submit', { headers: { 'X-Review-Token': token } });
          const reviewedData = await reviewedRes.json();
          if (reviewedData.reviewedMembers) setReviewedMembers(reviewedData.reviewedMembers);
        }
      } catch (e) {}
      setLoading(false);
    };
    checkAuth();
  }, []);

  const isSelfReview = (email: string) => user?.email?.toLowerCase() === email.toLowerCase();

  if (loading) return <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-[#002868] to-[#BF0A30]"><div className="text-white">Loading...</div></div>;
  
  if (!user) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-[#002868] to-[#BF0A30] p-4">
        <div className="bg-white p-8 rounded-xl shadow-lg max-w-md w-full text-center">
          <h1 className="text-2xl font-bold text-[#002868] mb-4">360° Review</h1>
          <p className="text-gray-600 mb-6">Arizona DeMolay State Association</p>
          <button onClick={() => window.location.href = '/api/auth/google'} className="w-full py-3 bg-gradient-to-r from-[#002868] to-[#003d87] text-white rounded-lg font-semibold">Sign in with Google</button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#002868] to-[#BF0A30] p-4">
      <main className="max-w-4xl mx-auto">
        <div className="bg-white rounded-xl shadow-lg overflow-hidden">
          <div className="bg-gradient-to-r from-[#002868] to-[#003d87] p-6 text-white flex justify-between items-center">
            <div>
              <h1 className="text-2xl font-bold">360° Review</h1>
              <p className="text-blue-200">Arizona DeMolay State Association</p>
            </div>
            <div className="text-right">
              <p className="font-medium">{user.name}</p>
              <button onClick={() => { localStorage.removeItem('reviewToken'); setUser(null); }} className="text-sm text-blue-200 hover:text-white">Logout</button>
            </div>
          </div>

          <div className="p-6">
            <div className="mb-6 p-4 bg-gray-50 rounded-lg">
              <p className="text-gray-600">Progress: <span className="font-bold text-[#002868]">{reviewedMembers.length}</span> of <span className="font-bold">{members.length}</span> reviewed</p>
              <div className="mt-2 h-2 bg-gray-200 rounded-full"><div className="h-full bg-gradient-to-r from-[#002868] to-[#BF0A30] rounded-full transition-all" style={{ width: `${(reviewedMembers.length / members.length) * 100}%` }} /></div>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              {members.map((member) => {
                const isReviewed = reviewedMembers.includes(member.id);
                const selfReview = isSelfReview(member.email);
                return (
                  <Link key={member.id} to={selfReview ? '#' : `/review/${member.id}`} onClick={(e) => { if (selfReview) e.preventDefault(); }} className={`block p-4 rounded-xl border-l-4 transition-all ${selfReview ? 'bg-gray-100 border-gray-400 opacity-60' : 'bg-white border-[#002868] shadow-md hover:shadow-lg'}`}>
                    <div className="flex items-center gap-4">
                      <div className={`w-12 h-12 rounded-full flex items-center justify-center text-lg font-bold ${isReviewed ? 'bg-green-500 text-white' : 'bg-gradient-to-br from-[#FFD700] to-[#B87333] text-[#002868]'}`}>
                        {isReviewed ? <CheckCircle className="w-6 h-6" /> : member.name.charAt(0)}
                      </div>
                      <div className="flex-1">
                        <h3 className="font-semibold text-[#002868]">{member.name}</h3>
                        <p className="text-sm text-gray-600">{member.title}</p>
                      </div>
                      <div>
                        {selfReview ? <span className="flex items-center gap-1 px-3 py-1 bg-gray-200 text-gray-500 rounded-full text-sm"><Lock className="w-4 h-4" /> Self</span> :
                         isReviewed ? <span className="flex items-center gap-1 px-3 py-1 bg-green-100 text-green-700 rounded-full text-sm"><CheckCircle className="w-4 h-4" /> Done</span> :
                         <span className="flex items-center gap-1 px-3 py-1 bg-gradient-to-r from-[#BF0A30] to-[#d41a3f] text-white rounded-full text-sm"><ChevronRight className="w-4 h-4" /> Review</span>}
                      </div>
                    </div>
                  </Link>
                );
              })}
            </div>

            {reviewedMembers.length === members.length && (
              <div className="mt-6 text-center">
                <Link to="/results" className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-[#002868] to-[#003d87] text-white rounded-lg font-semibold">View All Results</Link>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}